# Generated by Django 4.2.3 on 2023-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
    ]
