# Generated by Django 4.2.4 on 2023-08-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_post_code_order_postal_code_order_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="country_code",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
